"""add invoice id to jobs

Revision ID: 16ae5fbcae6b
Revises: 7e709fc1cfc9
Create Date: 2026-09-11 16:48:39.317528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ae5fbcae6b'
down_revision: Union[str, Sequence[str], None] = '7e709fc1cfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'invoice_id')
    # ### end Alembic commands ###
