"""change invoice date to date

Revision ID: b9ded8388b47
Revises: 
Create Date: 2026-09-11 00:54:15.952004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ded8388b47'
down_revision: Union[str, Sequence[str], None] = "f2f4a1b50cb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "invoices",
        "invoice_date",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Date(),
        existing_nullable=True,
        postgresql_using="""
            CASE
                WHEN invoice_date ~ '^\\d{4}-\\d{2}-\\d{2}$'
                    THEN invoice_date::date
                WHEN invoice_date ~ '^\\d{2}-\\d{2}-\\d{4}$'
                    THEN to_date(invoice_date, 'DD-MM-YYYY')
                WHEN invoice_date ~ '^\\d{2}/\\d{2}/\\d{4}$'
                    THEN to_date(invoice_date, 'DD/MM/YYYY')
                WHEN invoice_date ~ '^\\d{2}\\.\\d{2}\\.\\d{4}$'
                    THEN to_date(invoice_date, 'DD.MM.YYYY')
                ELSE NULL
            END
        """
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
